spring:
  application:
    name: restaurant-api
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: restaurantr1
          predicates:
            - Path=/api/v1/restaurant/**
          uri: lb://RESTAURANT
server:
  port: ${app.port:8080}
  tomcat:
    threads:
      max: 200
      min-spare: 50
    max-connections: 500
    max-keep-alive-requests: 200
    keep-alive-timeout: 120s
    max-swallow-size: 4000
